djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resa.urls', namespace='resa')),
]

resa/urls.py
from django.urls import path, re_path

from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from . import views

app_name = 'resa'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Gestion du planning
    path('planning/', views.DiveList.as_view(), name='planning'),

    # Gestion des plongeures
    path('divers/', views.DiverList.as_view(), name='diver_list'),

    ## Gestion des sites
    re_path(r'^site/$', views.SiteList.as_view(), name='site_list'),
    re_path(r'^site/create/$', views.SiteCreate.as_view(), name="site_create"),
    re_path(r'^site/(?P<pk>\d+)/$', views.SiteDetail.as_view(), name="site_detail"),
    re_path(r'^site/(?P<pk>\d+)/update/$', views.SiteUpdate.as_view(), name="site_update"),
    re_path(r'^site/(?P<pk>\d+)/delete/$', views.SiteDelete.as_view(), name="site_delete"),
]

resa/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


# Create your models here.


class Site(models.Model):
    """
    Description des sites de plongée dispo
    name : nom du site
    description : Description du site de plangée
    depth : profondeur maximum du site
    """
    name = models.CharField(max_length=100)
    description = models.TextField()
    depth = models.IntegerField()

    class Meta:
        ordering = ('name', 'depth',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('resa:site_detail', args=[self.id])


class Dive(models.Model):
    """
    Description des sites de plongée prévues
    - date : date de la plongée
    - site : nom du site prévu
    - nbPlaces : nombre de places disponibles
    """

    date = models.DateTimeField()
    site = models.ForeignKey(Site,
                             on_delete=models.CASCADE,
                             related_name='site_dives')
    nbPlaces = models.IntegerField()

    class Meta:
        ordering = ('date',)

    def __str__(self):
        return self.site.name + str(self.date)


class Diver(AbstractUser):
    LEVEL_CHOICES = (
        ('P0', 'Aucun'),
        ('P1', 'Niveau 1'),
        ('P2', 'Niveau 2'),
        ('P3', 'Niveau 3'),
        ('E2', 'MF1'),
        ('E3', 'MF2'),
    )
    level = models.CharField(max_length=2,
                             choices=LEVEL_CHOICES,
                             default='P0')
    birth_date = models.DateField(null=True, blank=True)
    reservation = models.ManyToManyField(Dive, blank=True)

    class Meta:
        ordering = ('last_name', 'level',)

    def __str__(self):
        return self.last_name + self.first_name

resa/forms.py
from django import forms
from . import models
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class SiteForm(forms.ModelForm):
    class Meta:
        model = models.Site
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('save', 'Save'))

resa/views.py
from django.shortcuts import render
from .models import Dive, Diver, Site
from django.views.generic import ListView, TemplateView, DeleteView, CreateView, UpdateView, DetailView

from django.urls import reverse_lazy
from . import forms


# Create your views here.
# CRUD planning des plongée

class DiveList(ListView):
    queryset = Dive.objects.all()
    context_object_name = 'dives'
    template_name = 'resa/dive/list.html'


class DiveCreate(CreateView):
    pass


class DiveDetail(DetailView):
    pass


class DiveUpdate(UpdateView):
    pass


class DiveDelete(DeleteView):
    pass


# CRUD plongeurs
class DiverList(ListView):
    queryset = Diver.objects.all()
    context_object_name = 'divers'
    template_name = 'resa/diver/list.html'


class DiverCreate(CreateView):
    pass


class DiverDetail(DeleteView):
    pass


class DiverUpdate(UpdateView):
    pass


class DiverDelete(DeleteView):
    pass


## Site Views : CRUD
class SiteDetail(DetailView):
    context_object_name = "site"
    model = Site
    template_name = 'resa/site/site_detail.html'


class SiteCreate(CreateView):
    model = Site
    form_class = forms.SiteForm
    template_name = 'resa/site/site_form.html'


class SiteUpdate(UpdateView):
    model = Site
    form_class = forms.SiteForm


class SiteDelete(DeleteView):
    model = Site
    success_url = reverse_lazy("site_list")


class SiteList(ListView):
    model = Site
    queryset = Site.objects.all()
    context_object_name = 'sites'
    template_name = 'resa/site/site_list.html'

resa/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>

    <title>{% block title %}{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
{% include 'nav.html' %}
{% block header %}{% endblock header %}
<div class="container">
    {% block content %}{% endblock content %}
</div>

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}
</body>

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>

resa/templates/carousel.html
{% load static %}
<div class="container">
    <div id="demo" class="carousel slide" data-ride="carousel">

      <!-- Indicators -->
      <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
      </ul>

      <!-- The slideshow -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'imgs/img1.jpeg' %}" alt="Moorea" width="100%" height="300">
        </div>
        <div class="carousel-item">
          <img src="{% static 'imgs/img2.jpeg' %}" alt="Moorea" width="100%" height="300">
        </div>
        <div class="carousel-item">
          <img src="{% static 'imgs/img3.jpeg' %}" alt="Moorea" width="100%" height="300">
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>
    </div>
</div>

<style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 1000px;
    height: 400px;
  }
  </style>

resa/templates/footer.html
      <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Lion de Mer 2020</p>
    </div>
    <!-- /.container -->
  </footer>

resa/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}

{% endblock header %}


{% block content %}
<!-- Contenu de la page -->

<div class=container-fluid>
    <div class="row align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'imgs/img2.jpeg' %}" width="900px" height="400px" alt="">
        </div>
        <!-- /.col--lg-8 -->
        <div class="col-lg-5">
            <h1 class="font-weight-light">Bienvenu sur le site du Lion de Mer</h1>
            <p>Le club du Lion de Mer est un club associatif. Pour pouvoir accéder à ses activités,
                il faut être membre de l'association à jour de sa cotisation, et membre de la FFESSM. </p>
            <a class="btn btn-primary" href="{% url 'resa:login' %}">Accès Membre</a>
        </div>
        <!--  /.col-md-4 -->
    </div>
    <!-- /.row -->

    <div class="card text-white bg-secondary my-5 py-4 text-center">
      <div class="card-body">
        <p class="text-white m-0">Placer ici des informations importants (AG, changment de date de sortie,
            sortie exceptionelle, etc ...)</p>
      </div>
    </div>
</div>

    <!--Détails -->
    <div class="row">
    <div class="col-md-6 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h3 class="card-title">Nos prochaines explorations</h3>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary btn-sm">Plus de dates</a>
          </div>
        </div>

    </div>
    <div class="col-md-6 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h3 class="card-title">Stages et Formations</h3>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary btn-sm">Plus de dates</a>
          </div>
        </div>

    </div>
    </div>
{% endblock content %}

resa/templates/nav.html
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href=" {% url 'resa:home'%} ">Accueil</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Mon Profil</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'resa:planning' %}">Reservation</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%  url 'resa:site_list' %}">Nos Sites de plongée</a>
    </li>
  </ul>
</nav>

resa/templates/resa/dive/detail_site.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

resa/templates/resa/dive/list.html
{% extends 'base.html' %}

{% block title %}Resa Dive{% endblock %}

{% block content %}
    <h2>Planning des plongées</h2>
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th>Site</th>
            <th>Date</th>
            <th>Nb places</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            {% for dive in dives %}
                <tr>
                    <td><a href="{{ dive.site.get_absolute_url }}">{{ dive.site }}</a></td>
                    <td>{{ dive.date }}</td>
                    <td>{{ dive.nbPlaces }}</td>
                    <td><a href="#" class="btn btn-secondary" role="button">S'inscrire</a></td>
                </tr>

            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

resa/templates/resa/diver/list.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-hover">
        <thead class="thead-dark">
            <th>Nom</th>
            <th>Prenom</th>
            <th>Niveau</th>
        </thead>
    <tbody>
        {% for diver in divers %}
            <tr>
                <td>{{ diver.last_name }}</td>
                <td>{{ diver.first_name }}</td>
                <td>{{ diver.level }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>




{% endblock content %}

resa/templates/resa/site/detail.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

resa/templates/resa/site/site_detail.html
{% extends 'base.html' %}}

{% block content %}
<h1>Nom du site : {{ object.name }}</h1>
<h2>Description : </h2>
<p>{{ object.description }}</p>
{% endblock content %}

resa/templates/resa/site/site_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Nouveau Site : </h2>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

resa/templates/resa/site/site_list.html
{% extends 'base.html' %}

{% block title %}Nos sites de plongée{% endblock %}

{% block content %}
    <h2>Liste des sites</h2>
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th>Nom</th>
            <th>Description</th>
            <th>Profondeur max</th>
        </tr>
        </thead>
        <tbody>
            {% for site in sites %}
                <tr>
                    <td><a href="{{ site.get_absolute_url }}">{{ site.name }}</a></td>
                    <td>{{ site.description }}</td>
                    <td>{{ site.depth }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}